# The URL the site will be built for
base_url = "https://queenofsquiggles.github.io/"

title = "Queen Of Squiggles's Blog"
description = "The personal blog for all of the Queen's news, ramblings, portfolio stuffs, and more!"
default_language = "en"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zolastrap"

generate_feeds = true
feed_filenames = ["rss.xml"]

author = "Queen Of Squiggles"

generate_robots_txt = true

taxonomies = [
  { name = "tags", feed = true, paginate_by = 15 },
  # { name = "categories", feed = true },
]


[slugify]
paths = "on"
taxonomies = "safe"
anchors = "safe"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = true
smart_punctuation = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
# async images
# lazy_async_image = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
include_description = true
include_date = true
include_path = true
include_content = true

[extra]
# Put all your custom variables here
theme = "cyborg"
search = "Search"
themes = ""                             # disables theme selection (which appears to be bugged anyway since forking the theme)
schemes = ""                            # disables scheme selection becuase it's kinda confusing
email = "thequeenofsquiggles@gmail.com"
date_format = '%Y/%m/%d'

mastodon = 'https://blobfox.coffee/@queenofsquiggles'

# footer icons
icons = [
  { title = 'Mastodon', icon = 'fab fa-mastodon', url = 'https://blobfox.coffee/@queenofsquiggles' },
  { title = "RSS Feed", icon = "fas fa-rss", url = "rss.xml" },
]

# navbar links
links = [{ title = "Tags", url = "tags" }, { title = 'About', url = 'about' }]
